apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: boudun/wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-service
            - name: WORDPRESS_DB_USER
              value: wordpressUser
            - name: WORDPRESS_DB_PASSWORD
              value: securepassword
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_AUTH_SALT
              value: patatechaude
          ports:
            - containerPort: 80
              name: http
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
