apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: boudun/wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-headless.default.svc.cluster.local
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-root-password
                  key: password
            - name: WORDPRESS_DB_USER
              value: root
          ports:
            - containerPort: 80
              name: http
      volumeMounts:
        - name: wordpress-data
          mountPath: /var/www/html
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
