apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: boudun/wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-headless.default.svc.cluster.local
          ports:
            - containerPort: 80
              name: http
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
