name: Deploy to EKS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-west-3
  EKS_CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
        
      - name: Injection des secrets depuis GitHub
        uses: GitOpsTech/secrets-sync@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_namespace: 
          secrets: |
            - name=WORDPRESS_DB_USER file=Secrets.yaml:WORDPRESS_DB_USER key=WORDPRESS_DB_USER
            - name=WORDPRESS_DB_PASSWORD file=Secrets.yaml:WORDPRESS_DB_PASSWORD key=WORDPRESS_DB_PASSWORD
            - name=WORDPRESS_DB_NAME file=Secrets.yaml:WORDPRESS_DB_NAME key=WORDPRESS_DB_NAME
            - name=WORDPRESS_AUTH_SALT file=Secrets.yaml:WORDPRESS_AUTH_SALT key=WORDPRESS_AUTH_SALT

      - name: Deploy to EKS
        run:
          kubectl apply -f ./